[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/go-telegram-bot-api/telegram-bot-api"
  version = "4.6.2"

[[constraint]]
  name = "github.com/shuienko/go-pihole"
  branch = "master"